### ISSUE TITLE
Searchpage  - Categories Navigation Backend

### ISSUE THREAD

**Issue by hjconehour** [1hour1day/onehouraday#22]
As a volunteer I would like to navigate through different categories so that I can discover new projects

**ACCEPTANCE CRITERIA**
- A list of categories is displayed
- When user clicks on a category the listing is refreseh

Categories:

- Health
- Poverty
- Hungry
- Education
- Environent
- Peace
- Justice
- Animals
- Business
- Human Rights
- Equality
- Others

**WIREFRAME**
![2listing_navigation](https://user-images.githubusercontent.com/3884690/35197379-c3e7bb36-fede-11e7-983f-cd3e09dcaa9f.png)

**Comment by darrenjl** [comment]
Pull request submitted for backend

**Comment by hjconehour** [comment]
This mockup is old.

**Comment by darrenjl** [comment]
Reducing scope of this issue to backend only and marking as closed.
