### ISSUE TITLE
Search page - Filtering

### ISSUE THREAD

**Issue by hjconehour** [1hour1day/onehouraday#28]
As a volunteer I would like to be able to filter the projects so that I can easily find what I am looking for

**ACCEPTANCE CRITERIA**
Let user filter by location
Let user filter by Skills
Let user filter by Category

**WIREFRAME**
![projects listing](https://user-images.githubusercontent.com/3884690/35776177-1c587ec2-0998-11e8-874e-1fef6bf7e4ce.png)

**Comment by ginna-baker** [comment]
@hjconehour I could start the backend for this while we wait for Bowie to get back to us with the front-end.

Here's what I'd need: Say I start with locations.  What locations would you like to offer?  Do you plan to import some kind of giant spreadsheet of cities / regions / countries?  

Same question for Categories -- what are the categories?

Skills -- what are the skills?

The one issue I see with the design here is that these are all dropdowns.  You don't want to have a dropdown that is too long, gets really difficult for the user to navigate.  I guess I need to see the lists before I say for sure that this won't work, but I suspect the location one is going to have problems and probably the other two as well.  We may want to switch the design to a tags input like this:

![screen shot 2018-02-26 at 9 44 58 pm](https://user-images.githubusercontent.com/6732956/36707907-5ea42e68-1b3e-11e8-9e3f-5d0bd47209fe.jpg)

**Comment by hjconehour** [comment]
` I could start the backend for this while we wait for Bowie to get back to us with the front-end.
`Great!  Just consider this is not part of the MVP. Is more arround the full version. I think is great if you can start working on this if the other ticket from the MVP are blocked :(


> `Here's what I'd need: Say I start with locations. What locations would you like to offer? Do you plan to import some kind of giant spreadsheet of cities / regions / countries?`
We will launch for 1 country: USA
Can we use open-streemap to pick regions and cities?

> Same question for Categories -- what are the categories?
I will create a list. 

> Skills -- what are the skills?
Skills we will complex because there are different types of skills per role. I need to review the complete flow (from publish to findability)

Still this in conceptual design.  Let's check how Linkedin resolves the same problem and use a similar approach. 

There are 2 options

a) Fixed list 
b) People can enter free text, we use autocomplete to avoid duplicates. And the list is created by users. 



> The one issue I see with the design here is that these are all dropdowns. You don't want to have a dropdown that is too long, gets really difficult for the user to navigate. I guess I need to see the lists before I say for sure that this won't work, but I suspect the location one is going to have problems and probably the other two as well. We may want to switch the design to a tags input like this:

Makes sense.  I will work on the interaction of this. We can use this approach. 

https://www.zillow.com/homes/for_sale/Casa-Loma-Alta-CA_rb/?fromHomePage=true&shouldFireSellPageImplicitClaimGA=false&fromHomePageTab=buy
