### ISSUE TITLE
Determine whether live-server is needed as a dependency 

### ISSUE THREAD

**Issue by djm158** [1hour1day/onehouraday#42]
`npm run serve` currently tries to serve files from `public/` in the root of the directory, but should point to `frontend/public/`

current:
```json
"serve": "live-server public/",
```

proposed change:
```json
"serve": "live-server frontend/public/",
```

**Comment by andrewhwang10** [comment]
Currently I'm running a local mongod server in a separate terminal and then running `npm run start` in the root of the project directory.

**Comment by djm158** [comment]
For the back end or front end?

**Comment by andrewhwang10** [comment]
Backend I believe but you're right we should change the path to the directory for serve

**Comment by djm158** [comment]
Running `npm run dev-server` also works for a live reload front end server so maybe the dependency on `live-server` can be removed?

**Comment by andrewhwang10** [comment]
Maybe, because `live-server` also doesn't automatically rebuild using webpack so no changes showup when developing frontend

**Comment by djm158** [comment]
I'm closing this since webpack-dev-server is configured
