### ISSUE TITLE
Project active? Slack invite?

### ISSUE THREAD

**Issue by akullpp** [1hour1day/onehouraday#80]
Hi guys,

me and a friend had a quite similar idea and I wanted to help you with your project. Unfortunately the email (hernan@1hour1day.com) in your wiki for the slack invite is invalid. So can you invite me?

Can you tell me whether your project is still active or not? If it's not I would take your idea and implement it myself. I have quite the experience and it shouldn't be an issue.

**Comment by hjconehour** [comment]
Hi Andreas,

We are looking for sr tech people who can re-take this project.

I will send you a private email to explain all the details about the
project status.

Thanks a lot!

Hernan
